version: "3.1"

services:
  # watchtower:
  #     context: .
  #     dockerfile: client/Dockerfile
  #   restart: always
  #   ports:
  #     - 8081:
  #   depends_on:
  #     - letsencrypt

  front-end:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always
    depends_on:
      - letsencrypt

  letsencrypt:
    image: linuxserver/letsencrypt:0.36.0-ls46
    container_name: letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/config
      - ./docker-config/nginx.conf:/config/nginx/site-confs/default
    environment:
      - EMAIL=deeson@deficustody.com
      - URL=deficustody.com
      - SUBDOMAINS=www
      - VALIDATION=http
